In [9]:
!pip install sentence-transformers

In [2]:
import pandas as pd
import re
import nltk
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer
from sentence_transformers import SentenceTransformer
import ast
import faiss
# import json

In [ ]:
nltk.download('punkt_tab')
nltk.download('stopwords')

# Load to Memory & Merge Features and Desc.

In [86]:
games_df = pd.read_csv('games.csv')
metadata_df = pd.read_json('games_metadata.json', lines=True)

df = pd.merge(games_df, metadata_df, on='app_id', how='inner')

games_df = None
metadata_df = None

In [ ]:
# df.to_csv('Altered CSVs/merged_game_data.csv', index=False)

# MultiLabelBinarizer

In [66]:
# df = pd.read_csv('Altered CSVs/merged_game_data.csv')

In [87]:
mlb = MultiLabelBinarizer()

# Convert the 'tags' column from a string representation of a list to an actual list
df['tags'] = df['tags'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

tag_matrix = mlb.fit_transform(df['tags'])

tags_df = pd.DataFrame(tag_matrix, columns=mlb.classes_)

df = pd.concat([df, tags_df], axis=1)

In [69]:
tags_df.head(5)

,1980s,1990's,2.5D,2D,2D Fighter,2D Platformer,360 Video,3D,3D Fighter,3D Platformer,...,Well-Written,Werewolves,Western,Wholesome,Word Game,World War I,World War II,Wrestling,Zombies,eSports
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# df.to_csv('Altered CSVs/MutliLabelBinarized.csv', index=False)

# Preprocessing

## Cleaning

Fill Empty Descriptions -> Clean All Descriptions (Remove Special Characters and Links)<br>
-> Fill Now Empty Descriptions that were made up of Special Characters -> Clean newly filled descriptions

In [111]:
df = pd.read_csv('Altered CSVs/MutliLabelBinarized.csv')

In [112]:
def clean_text(text):
    # Remove Special Characters
    text = re.sub(r'[^\w\s]', '', text)

    # Sets all characters to lowercase
    text = text.lower()

    # Removes URLs beginning with https, http, or www
    text = re.sub(r'https\S+|http\S+|www\S+', '', text, flags=re.MULTILINE)
    
    return text

In [113]:
# Fill Empty Descriptions
df['description'] = df['description'].fillna(df['title'] +' '+ str(df['tags']))

In [114]:
df['description'] = df['description'].apply(clean_text)

In [115]:
rows = df['description'].str.strip() == ''

df.loc[rows, 'description'] = df['title'] +' '+ str(df['tags'])

df.loc[rows, 'description'] = df['description'].apply(clean_text)

In [107]:
# Print any rows with descriptions with only whitespace characters
empty_descriptions = df[df['description'].str.strip() == '']
empty_descriptions

Empty DataFrame
Columns: [app_id, title, date_release, win, mac, linux, rating, positive_ratio, user_reviews, price_final, price_original, discount, steam_deck, description, tags, 1980s, 1990's, 2.5D, 2D, 2D Fighter, 2D Platformer, 360 Video, 3D, 3D Fighter, 3D Platformer, 3D Vision, 4 Player Local, 4X, 6DOF, 8-bit Music, ATV, Abstract, Action, Action RPG, Action RTS, Action Roguelike, Action-Adventure, Addictive, Adventure, Agriculture, Aliens, Alternate History, Ambient, America, Animation & Modeling, Anime, Arcade, Archery, Arena Shooter, Artificial Intelligence, Assassin, Asymmetric VR, Asynchronous Multiplayer, Atmospheric, Audio Production, Auto Battler, Automation, Automobile Sim, BMX, Base Building, Baseball, Based On A Novel, Basketball, Battle Royale, Beat 'em up, Beautiful, Benchmark, Bikes, Blood, Board Game, Boss Rush, Bowling, Boxing, Building, Bullet Hell, Bullet Time, CRPG, Capitalism, Card Battler, Card Game, Cartoon, Cartoony, Casual, Cats, Character Action Game, Character Customization, Chess, Choices Matter, Choose Your Own Adventure, Cinematic, City Builder, Class-Based, Classic, Clicker, Co-op, Co-op Campaign, Coding, Cold War, Collectathon, Colony Sim, ...]
Index: []

[0 rows x 456 columns]

In [108]:
null_literal_descriptions = df[df['description'].str.strip() == 'null']
null_literal_descriptions

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,...,Well-Written,Werewolves,Western,Wholesome,Word Game,World War I,World War II,Wrestling,Zombies,eSports
29524,930840,东方百问~TouHouAsked,2018-10-07,True,False,False,Positive,93,29,0.99,...,0,0,0,0,0,0,0,0,0,0

In [109]:
# Print Fixed Descriptions
df.loc[rows, 'description']

14865    elechead 0        action adventure parkour thi...
25173    his heroes in the sky 0        action adventur...
44906    our elusive suffering 0        action adventur...
Name: description, dtype: object

In [110]:
# Checking Random Description Columns
pd.set_option('display.max_colwidth', None)
print(df['description'].sample(n=3))
pd.reset_option('display.max_colwidth')

40609    ready to start anew build a village from scratch in seeds of resilience learn to choose the right items understand natures patterns use real lifebased constructions and craft techniques in this turnbased tycoon game
45492                                                                                                            help kingmeow to collect gold to increase your cat speed and make the higher score in this precision platformer
26785                                                                                           open world werewolf hunt in coop and singleplayer prepare for the werewolfhunt with many threats in the deep forest of lovengrad
Name: description, dtype: object

In [ ]:
# df.to_csv('Altered CSVs/after_cleaning.csv', index=False)

## Tokenization & Lemmatization

In [ ]:
# df = pd.read_csv('Altered CSVs/after_cleaning.csv')

In [117]:
# Tokenize the descriptions
df['tokens'] = df['description'].apply(word_tokenize)

# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [118]:
# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

In [119]:
# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [120]:
# df.to_csv('Altered CSVs/after_tokenization.csv', index=False)

# Sentance Transformer / Embeddings

In [ ]:
# df = pd.read_csv('Altered CSVs/MutliLabelBinarized.csv')

In [121]:
model = SentenceTransformer('all-MiniLM-L6-v2')

df['title'] = df['title'].fillna('')
df['description'] = df['description'].fillna('')

texts = (df['title'] + ' ' + df['description'] + ' ' + df['tags']).tolist()

text_embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)

df['embedding'] = list(text_embeddings)

Batches:   0%|          | 0/1590 [00:00<?, ?it/s]

c:\Users\vince\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [122]:
# df.to_csv('Altered CSVs/with_embeddings.csv', index=False)

# Normalization

## Min-Max

In [ ]:
# df = pd.read_csv('Altered CSVs/with_embeddings.csv')

**Applied for Ratings**

In [123]:
rating_dict = {
    'Overwhelmingly Positive': 9,
    'Very Positive': 8,
    'Positive': 7,
    'Mostly Positive': 6,
    'Mixed': 5,
    'Mostly Negative': 4,
    'Negative': 3,
    'Very Negative': 2,
    'Overwhelmingly Negative': 1
}

df['rating_normalized'] = (df['rating'].map(rating_dict) - 1) / 8

## Log Normalizing

**Applied for Positive Ratio, Price, and Review Count**

In [124]:
df['positive_ratio_log'] = np.log1p(df['positive_ratio'])
df['price_log'] = np.log1p(df['price_final'])
df['user_reviews_log'] = np.log1p(df['user_reviews'])

In [125]:
# df.to_csv('Altered CSVs/normalized.csv', index=False)

# Concatenating Features

In [2]:
# df = pd.read_csv('Altered CSVs/normalized.csv')

In [ ]:
embeddings = text_embeddings

tags = tag_matrix

numerics = df[['price_log', 'positive_ratio_log', 'user_reviews_log']].values

X = np.hstack([numerics, embeddings, tags])

cs_matrix = cosine_similarity(X)

np.savetxt('hstack_data.txt', X, delimiter=',')
np.save("cs_matrix.npy", cs_matrix)

# Cosine Similarity

In [9]:
df = pd.read_csv('Altered CSVs/merged_game_data.csv')
df.head(0)

Empty DataFrame
Columns: [app_id, title, date_release, win, mac, linux, rating, positive_ratio, user_reviews, price_final, price_original, discount, steam_deck, description, tags, Naval Combat, Mining, Submarine, Design & Illustration, Jet, Stealth, Card Game, Hunting, Intentionally Awkward Controls, Life Sim, Pirates, Psychological Horror, Animation & Modeling, Colony Sim, 3D Platformer, Card Battler, Based On A Novel, Tower Defense, Singleplayer, Science, Fighting, Combat Racing, Top-Down, Combat, Hockey, Post-apocalyptic, Game Development, On-Rails Shooter, 4X, Hentai, 2D Fighter, Party-Based RPG, Choose Your Own Adventure, Metroidvania, Real-Time with Pause, Hand-drawn, Action, Addictive, JRPG, Mars, Loot, Naval, PvP, Nudity, First-Person, RPG, Medical Sim, Agriculture, Puzzle, Robots, Sandbox, 6DOF, Spectacle fighter, Twin Stick Shooter, Philosophical, 360 Video, Turn-Based Strategy, Hacking, CRPG, Immersive, Sokoban, Lore-Rich, Puzzle Platformer, Trading Card Game, Dungeon Crawler, Grid-Based Movement, Realistic, Narrative, Sniper, Great Soundtrack, Clicker, Tennis, Diplomacy, Team-Based, Hero Shooter, TrackIR, Open World, Sailing, Drama, Cricket, Fast-Paced, Tile-Matching, Time Manipulation, Outbreak Sim, Sequel, ...]
Index: []

[0 rows x 456 columns]

In [ ]:
cs_matrix = np.load("cs_matrix.npy")

In [23]:
def recommend(df, appid, cs_matrix, k=10):
    index = df[df['app_id'] == appid].index[0]
    scores = cs_matrix[index].copy()
    scores[index] = -np.inf
    return np.argsort(scores)[-k:][::-1]

In [24]:
kf2 = recommend(df, 210945, cs_matrix)
kf2

array([14256, 11700, 12036, 14263, 14694, 13008, 40325, 18746, 12037,
       31633], dtype=int64)