In [ ]:
!pip install sentence-transformers
pip install streamlit

In [ ]:
import pandas as pd
import re
import nltk
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer
from sentence_transformers import SentenceTransformer
import ast
import faiss
# import streamlit
# import json

In [ ]:
nltk.download('punkt_tab')
nltk.download('stopwords')

# Load to Memory & Merge Features and Desc.

In [2]:
games_df = pd.read_csv('games.csv')
metadata_df = pd.read_json('games_metadata.json', lines=True)

df = pd.merge(games_df, metadata_df, on='app_id', how='inner')

games_df = None
metadata_df = None

In [ ]:
# df.to_csv('Altered CSVs/merged_game_data.csv', index=False)

# MultiLabelBinarizer

In [66]:
# df = pd.read_csv('Altered CSVs/merged_game_data.csv')

In [3]:
mlb = MultiLabelBinarizer()

# Convert the 'tags' column from a string representation of a list to an actual list
df['tags'] = df['tags'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

tag_matrix = mlb.fit_transform(df['tags'])

tags_df = pd.DataFrame(tag_matrix, columns=mlb.classes_)

df = pd.concat([df, tags_df], axis=1)

In [69]:
tags_df.head(5)

,1980s,1990's,2.5D,2D,2D Fighter,2D Platformer,360 Video,3D,3D Fighter,3D Platformer,...,Well-Written,Werewolves,Western,Wholesome,Word Game,World War I,World War II,Wrestling,Zombies,eSports
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# df.to_csv('Altered CSVs/MutliLabelBinarized.csv', index=False)

# Preprocessing

## Cleaning

Fill Empty Descriptions -> Clean All Descriptions (Remove Special Characters and Links)<br>
-> Fill Now Empty Descriptions that were made up of Special Characters -> Clean newly filled descriptions

In [ ]:
# df = pd.read_csv('Altered CSVs/MutliLabelBinarized.csv')

In [4]:
def clean_text(text):
    # Remove Special Characters
    text = re.sub(r'[^\w\s]', '', text)

    # Sets all characters to lowercase
    text = text.lower()

    # Removes URLs beginning with https, http, or www
    text = re.sub(r'https\S+|http\S+|www\S+', '', text, flags=re.MULTILINE)
    
    return text

In [5]:
# Fill Empty Descriptions
df['description'] = df['description'].fillna(df['title'] +' '+ str(df['tags']))

In [6]:
df['description'] = df['description'].apply(clean_text)

In [7]:
rows = df['description'].str.strip() == ''

df.loc[rows, 'description'] = df['title'] +' '+ str(df['tags'])

df.loc[rows, 'description'] = df['description'].apply(clean_text)

In [14]:
# Print any rows with descriptions with only whitespace characters
empty_descriptions = df[df['description'].str.strip() == '']
empty_descriptions

Empty DataFrame
Columns: [app_id, title, date_release, win, mac, linux, rating, positive_ratio, user_reviews, price_final, price_original, discount, steam_deck, description, tags, 1980s, 1990's, 2.5D, 2D, 2D Fighter, 2D Platformer, 360 Video, 3D, 3D Fighter, 3D Platformer, 3D Vision, 4 Player Local, 4X, 6DOF, 8-bit Music, ATV, Abstract, Action, Action RPG, Action RTS, Action Roguelike, Action-Adventure, Addictive, Adventure, Agriculture, Aliens, Alternate History, Ambient, America, Animation & Modeling, Anime, Arcade, Archery, Arena Shooter, Artificial Intelligence, Assassin, Asymmetric VR, Asynchronous Multiplayer, Atmospheric, Audio Production, Auto Battler, Automation, Automobile Sim, BMX, Base Building, Baseball, Based On A Novel, Basketball, Battle Royale, Beat 'em up, Beautiful, Benchmark, Bikes, Blood, Board Game, Boss Rush, Bowling, Boxing, Building, Bullet Hell, Bullet Time, CRPG, Capitalism, Card Battler, Card Game, Cartoon, Cartoony, Casual, Cats, Character Action Game, Character Customization, Chess, Choices Matter, Choose Your Own Adventure, Cinematic, City Builder, Class-Based, Classic, Clicker, Co-op, Co-op Campaign, Coding, Cold War, Collectathon, Colony Sim, ...]
Index: []

[0 rows x 456 columns]

In [20]:
# The app Descripition is literally null
# null_literal_descriptions = df[df['description'].str.strip() == 'null']
# null_literal_descriptions

In [16]:
# Print Fixed Descriptions
df.loc[rows, 'description']

1        brink agents of change 0        action adventu...
7        men of war assault squad 2  deluxe edition upg...
18       borderlands 2 headhunter 4 wedding day massacr...
21       sniper elite 3  camouflage weapons pack 0     ...
30       the house in fata morgana original soundtrack ...
                               ...
50866    train sim world 4 0        action adventure pa...
50867    i expect you to die 3 cog in the machine 0    ...
50868    payday 3 0        action adventure parkour thi...
50869    eternights 0        action adventure parkour t...
50871    fatalzone 0        action adventure parkour th...
Name: description, Length: 10376, dtype: object

In [110]:
# Checking Random Description Columns
pd.set_option('display.max_colwidth', None)
print(df['description'].sample(n=3))
pd.reset_option('display.max_colwidth')

40609    ready to start anew build a village from scratch in seeds of resilience learn to choose the right items understand natures patterns use real lifebased constructions and craft techniques in this turnbased tycoon game
45492                                                                                                            help kingmeow to collect gold to increase your cat speed and make the higher score in this precision platformer
26785                                                                                           open world werewolf hunt in coop and singleplayer prepare for the werewolfhunt with many threats in the deep forest of lovengrad
Name: description, dtype: object

In [ ]:
# df.to_csv('Altered CSVs/after_cleaning.csv', index=False)

## Tokenization & Lemmatization

In [ ]:
# df = pd.read_csv('Altered CSVs/after_cleaning.csv')

In [8]:
# Tokenize the descriptions
df['tokens'] = df['description'].apply(word_tokenize)

# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [9]:
# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

In [10]:
# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [120]:
# df.to_csv('Altered CSVs/after_tokenization.csv', index=False)

# Sentance Transformer / Embeddings

In [ ]:
# df = pd.read_csv('Altered CSVs/MutliLabelBinarized.csv')

In [17]:
model = SentenceTransformer('all-MiniLM-L6-v2')

df['title'] = df['title'].fillna('')
df['description'] = df['description'].fillna('')

# Ensure tags (which are lists) are converted to a single string before concatenation
df['tags_text'] = df['tags'].apply(
    lambda x: ' '.join(x) if isinstance(x, (list, tuple)) else str(x)
)

texts = (df['title'] + ' ' + df['description'] + ' ' + df['tags_text']).tolist()

text_embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)

df['embedding'] = list(text_embeddings)

Batches:   0%|          | 0/1590 [00:00<?, ?it/s]

c:\Users\vince\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [122]:
# df.to_csv('Altered CSVs/with_embeddings.csv', index=False)

# Normalization

## Min-Max

In [ ]:
# df = pd.read_csv('Altered CSVs/with_embeddings.csv')

**Applied for Ratings**

In [18]:
rating_dict = {
    'Overwhelmingly Positive': 9,
    'Very Positive': 8,
    'Positive': 7,
    'Mostly Positive': 6,
    'Mixed': 5,
    'Mostly Negative': 4,
    'Negative': 3,
    'Very Negative': 2,
    'Overwhelmingly Negative': 1
}

df['rating_normalized'] = (df['rating'].map(rating_dict) - 1) / 8

## Log Normalizing

**Applied for Positive Ratio, Price, and Review Count**

In [19]:
df['positive_ratio_log'] = np.log1p(df['positive_ratio'])
df['price_log'] = np.log1p(df['price_final'])
df['user_reviews_log'] = np.log1p(df['user_reviews'])

In [125]:
# df.to_csv('Altered CSVs/normalized.csv', index=False)

# Concatenating Features

In [2]:
# df = pd.read_csv('Altered CSVs/normalized.csv')

In [ ]:
embeddings = text_embeddings

tags = tag_matrix

numerics = df[['price_log', 'positive_ratio_log', 'user_reviews_log']].values

X = np.hstack([numerics*0.4, embeddings*0.2, tags*1.0])

cs_matrix = cosine_similarity(X)

# np.save('hstack_data.npy', X)

np.save('cs_matrix.npy', cs_matrix)

# Cosine Similarity

In [3]:
df = pd.read_csv('Altered CSVs/merged_game_data.csv')
df.head(0)

Empty DataFrame
Columns: [app_id, title, date_release, win, mac, linux, rating, positive_ratio, user_reviews, price_final, price_original, discount, steam_deck, description, tags, Naval Combat, Mining, Submarine, Design & Illustration, Jet, Stealth, Card Game, Hunting, Intentionally Awkward Controls, Life Sim, Pirates, Psychological Horror, Animation & Modeling, Colony Sim, 3D Platformer, Card Battler, Based On A Novel, Tower Defense, Singleplayer, Science, Fighting, Combat Racing, Top-Down, Combat, Hockey, Post-apocalyptic, Game Development, On-Rails Shooter, 4X, Hentai, 2D Fighter, Party-Based RPG, Choose Your Own Adventure, Metroidvania, Real-Time with Pause, Hand-drawn, Action, Addictive, JRPG, Mars, Loot, Naval, PvP, Nudity, First-Person, RPG, Medical Sim, Agriculture, Puzzle, Robots, Sandbox, 6DOF, Spectacle fighter, Twin Stick Shooter, Philosophical, 360 Video, Turn-Based Strategy, Hacking, CRPG, Immersive, Sokoban, Lore-Rich, Puzzle Platformer, Trading Card Game, Dungeon Crawler, Grid-Based Movement, Realistic, Narrative, Sniper, Great Soundtrack, Clicker, Tennis, Diplomacy, Team-Based, Hero Shooter, TrackIR, Open World, Sailing, Drama, Cricket, Fast-Paced, Tile-Matching, Time Manipulation, Outbreak Sim, Sequel, ...]
Index: []

[0 rows x 456 columns]

In [ ]:
X = np.load("hstack_data.npy")
cs_matrix = np.load('cs_matrix.npy')

In [4]:
np.save('cs_matrix.npy', cs_matrix)

In [14]:
def recommend(df, appid, cs_matrix, k=10):
    
    index = df[df['app_id'] == appid].index[0]
    pos = df.index.get_loc(index)
    
    scores = cs_matrix[pos].copy()
    scores[pos] = -np.inf

    indexes = np.argsort(scores)[-k:][::-1]
    return df.iloc[indexes]

In [15]:
# Killing Floor - Mrs Foster Pack
rec = recommend(df, 210945, cs_matrix)
rec

IndexError: index 2604 is out of bounds for axis 0 with size 828

In [ ]:
# ELDEN RING
rec = recommend(df, 1245620, cs_matrix)
rec

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,...,Dog,Crowdfunded,Underground,Competitive,Faith,8-bit Music,Arcade,Relaxing,Lemmings,Emotional
14163,1091500,Cyberpunk 2077,2020-12-09,True,False,False,Very Positive,80,557051,60.0,...,0,0,0,0,0,0,0,0,0,0
12689,1063730,New World,2021-09-28,True,False,False,Mostly Positive,70,222345,40.0,...,0,0,0,0,0,0,0,0,0,0
13803,221100,DayZ,2018-12-13,True,False,False,Mostly Positive,74,296845,45.0,...,0,0,0,0,0,0,0,0,0,0
14770,1086940,Baldur's Gate 3,2023-08-03,True,True,False,Overwhelmingly Positive,95,269840,60.0,...,0,0,0,0,0,0,0,0,0,0
12658,594650,Hunt: Showdown,2019-08-27,True,False,False,Very Positive,83,136385,40.0,...,0,0,0,0,0,0,0,0,0,0
15097,782330,DOOM Eternal,2020-03-19,True,False,False,Very Positive,91,153466,40.0,...,0,0,0,0,0,0,0,0,0,0
47609,281990,Stellaris,2016-05-09,True,True,True,Very Positive,88,107871,40.0,...,0,0,0,0,0,0,0,0,0,0
12618,513710,SCUM,2018-08-29,True,False,False,Mostly Positive,74,75107,40.0,...,0,0,0,0,0,0,0,0,0,0
12740,294100,RimWorld,2018-10-17,True,True,True,Overwhelmingly Positive,98,140668,35.0,...,0,0,0,0,0,0,0,0,0,0
14434,275850,No Man's Sky,2016-08-12,True,True,False,Mostly Positive,76,209971,60.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Titanfall 2
rec = recommend(df, 1237970, cs_matrix)
rec

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,...,Dog,Crowdfunded,Underground,Competitive,Faith,8-bit Music,Arcade,Relaxing,Lemmings,Emotional
3372,322170,Geometry Dash,2014-12-22,True,True,False,Very Positive,93,239081,4.0,...,0,0,0,0,0,0,0,0,0,0
47548,238320,Outlast,2013-09-04,True,True,True,Overwhelmingly Positive,96,75391,3.0,...,0,0,0,0,0,0,0,0,0,0
50781,945360,Among Us,2018-11-16,True,False,False,Very Positive,92,587821,3.0,...,0,0,0,0,0,0,0,0,0,0
47817,774171,Muse Dash,2019-06-19,True,True,False,Very Positive,90,86591,3.0,...,0,0,0,0,0,0,0,0,0,0
47791,431960,Wallpaper Engine,2018-11-01,True,False,False,Overwhelmingly Positive,98,637341,4.0,...,0,0,0,0,0,0,0,0,0,0
15281,1794680,Vampire Survivors,2022-10-20,True,True,False,Overwhelmingly Positive,98,197109,5.0,...,0,0,0,0,0,0,0,0,0,0
47790,433340,Slime Rancher,2017-08-01,True,True,True,Overwhelmingly Positive,97,97997,5.0,...,0,0,0,0,0,0,0,0,0,0
47394,3590,Plants vs. Zombies GOTY Edition,2009-05-05,True,True,False,Overwhelmingly Positive,97,100864,5.0,...,0,0,0,0,0,0,0,0,0,0
47647,304430,INSIDE,2016-07-07,True,True,False,Overwhelmingly Positive,96,45867,2.0,...,0,0,0,0,0,0,0,0,0,0
47777,414700,Outlast 2,2017-04-24,True,False,False,Very Positive,91,37496,4.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Insurgency Sandstorm
rec = recommend(df, 581320, cs_matrix)
rec

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,...,Dog,Crowdfunded,Underground,Competitive,Faith,8-bit Music,Arcade,Relaxing,Lemmings,Emotional
47933,582660,Black Desert,2017-05-24,True,False,False,Mostly Positive,76,49539,10.0,...,0,0,0,0,0,0,0,0,0,0
13504,22380,Fallout: New Vegas,2010-10-19,True,False,False,Overwhelmingly Positive,96,147417,10.0,...,0,0,0,0,0,0,0,0,0,0
47523,219740,Don't Starve,2013-04-23,True,True,True,Overwhelmingly Positive,96,87184,10.0,...,0,0,0,0,0,0,0,0,0,0
15278,960090,Bloons TD 6,2018-12-17,True,True,False,Overwhelmingly Positive,97,239938,14.0,...,0,0,0,0,0,0,0,0,0,0
14774,1118200,People Playground,2019-07-23,True,False,False,Overwhelmingly Positive,98,195164,10.0,...,0,0,0,0,0,0,0,0,0,0
47832,470220,UNO,2017-01-03,True,False,False,Mostly Positive,73,35495,10.0,...,0,0,0,0,0,0,0,0,0,0
47383,400,Portal,2007-10-10,True,True,True,Overwhelmingly Positive,98,117868,10.0,...,0,0,0,0,0,0,0,0,0,0
47561,239030,Papers Please,2013-08-08,True,True,True,Overwhelmingly Positive,97,57117,10.0,...,0,0,0,0,0,0,0,0,0,0
14166,220200,Kerbal Space Program,2015-04-27,True,True,True,Overwhelmingly Positive,95,94712,10.0,...,0,0,0,0,0,0,0,0,0,0
47381,500,Left 4 Dead,2008-11-17,True,True,False,Overwhelmingly Positive,96,41569,10.0,...,0,0,0,0,0,0,0,0,0,0