In [ ]:
!pip install sentence-transformers
pip install streamlit

In [1]:
import pandas as pd
import re
import nltk
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer
from sentence_transformers import SentenceTransformer
import ast
import faiss
from sklearn.decomposition import TruncatedSVD
# import streamlit
# import json

In [ ]:
nltk.download('punkt_tab')
nltk.download('stopwords')

# Load to Memory & Merge Features and Desc.

In [2]:
games_df = pd.read_csv('games.csv')
metadata_df = pd.read_json('games_metadata.json', lines=True)

df_og = pd.merge(games_df, metadata_df, on='app_id', how='inner')

games_df = None
metadata_df = None

In [ ]:
# df.to_csv('Altered CSVs/merged_game_data.csv', index=False)

# MultiLabelBinarizer

In [ ]:
# df = pd.read_csv('Altered CSVs/merged_game_data.csv')

In [3]:
df = df_og.copy()

In [4]:
mlb = MultiLabelBinarizer()

# Convert the 'tags' column from a string representation of a list to an actual list
df['tags'] = df['tags'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

tag_matrix = mlb.fit_transform(df['tags'])

tags_df = pd.DataFrame(tag_matrix, columns=mlb.classes_)

df = pd.concat([df, tags_df], axis=1)

In [69]:
tags_df.head(5)

,1980s,1990's,2.5D,2D,2D Fighter,2D Platformer,360 Video,3D,3D Fighter,3D Platformer,...,Well-Written,Werewolves,Western,Wholesome,Word Game,World War I,World War II,Wrestling,Zombies,eSports
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# df.to_csv('Altered CSVs/MutliLabelBinarized.csv', index=False)

# Preprocessing

## Cleaning

Fill Empty Descriptions -> Clean All Descriptions (Remove Special Characters and Links)<br>
-> Fill Now Empty Descriptions that were made up of Special Characters -> Clean newly filled descriptions

In [ ]:
# df = pd.read_csv('Altered CSVs/MutliLabelBinarized.csv')

In [5]:
def clean_text(text):
    # Remove Special Characters
    text = re.sub(r'[^\w\s]', '', text)

    # Sets all characters to lowercase
    text = text.lower()

    # Removes URLs beginning with https, http, or www
    text = re.sub(r'https\S+|http\S+|www\S+', '', text, flags=re.MULTILINE)
    
    return text

In [6]:
# Fill Empty Descriptions
df['description'] = df['description'].fillna(df['title'] +' '+ str(df['tags']))

In [7]:
df['description'] = df['description'].apply(clean_text)

In [8]:
rows = df['description'].str.strip() == ''

df.loc[rows, 'description'] = df['title'] +' '+ str(df['tags'])

df.loc[rows, 'description'] = df['description'].apply(clean_text)

In [14]:
# Print any rows with descriptions with only whitespace characters
empty_descriptions = df[df['description'].str.strip() == '']
empty_descriptions

Empty DataFrame
Columns: [app_id, title, date_release, win, mac, linux, rating, positive_ratio, user_reviews, price_final, price_original, discount, steam_deck, description, tags, 1980s, 1990's, 2.5D, 2D, 2D Fighter, 2D Platformer, 360 Video, 3D, 3D Fighter, 3D Platformer, 3D Vision, 4 Player Local, 4X, 6DOF, 8-bit Music, ATV, Abstract, Action, Action RPG, Action RTS, Action Roguelike, Action-Adventure, Addictive, Adventure, Agriculture, Aliens, Alternate History, Ambient, America, Animation & Modeling, Anime, Arcade, Archery, Arena Shooter, Artificial Intelligence, Assassin, Asymmetric VR, Asynchronous Multiplayer, Atmospheric, Audio Production, Auto Battler, Automation, Automobile Sim, BMX, Base Building, Baseball, Based On A Novel, Basketball, Battle Royale, Beat 'em up, Beautiful, Benchmark, Bikes, Blood, Board Game, Boss Rush, Bowling, Boxing, Building, Bullet Hell, Bullet Time, CRPG, Capitalism, Card Battler, Card Game, Cartoon, Cartoony, Casual, Cats, Character Action Game, Character Customization, Chess, Choices Matter, Choose Your Own Adventure, Cinematic, City Builder, Class-Based, Classic, Clicker, Co-op, Co-op Campaign, Coding, Cold War, Collectathon, Colony Sim, ...]
Index: []

[0 rows x 456 columns]

In [20]:
# The app Descripition is literally null
# null_literal_descriptions = df[df['description'].str.strip() == 'null']
# null_literal_descriptions

In [16]:
# Print Fixed Descriptions
df.loc[rows, 'description']

1        brink agents of change 0        action adventu...
7        men of war assault squad 2  deluxe edition upg...
18       borderlands 2 headhunter 4 wedding day massacr...
21       sniper elite 3  camouflage weapons pack 0     ...
30       the house in fata morgana original soundtrack ...
                               ...
50866    train sim world 4 0        action adventure pa...
50867    i expect you to die 3 cog in the machine 0    ...
50868    payday 3 0        action adventure parkour thi...
50869    eternights 0        action adventure parkour t...
50871    fatalzone 0        action adventure parkour th...
Name: description, Length: 10376, dtype: object

In [110]:
# Checking Random Description Columns
pd.set_option('display.max_colwidth', None)
print(df['description'].sample(n=3))
pd.reset_option('display.max_colwidth')

40609    ready to start anew build a village from scratch in seeds of resilience learn to choose the right items understand natures patterns use real lifebased constructions and craft techniques in this turnbased tycoon game
45492                                                                                                            help kingmeow to collect gold to increase your cat speed and make the higher score in this precision platformer
26785                                                                                           open world werewolf hunt in coop and singleplayer prepare for the werewolfhunt with many threats in the deep forest of lovengrad
Name: description, dtype: object

In [ ]:
# df.to_csv('Altered CSVs/after_cleaning.csv', index=False)

## Tokenization & Lemmatization

In [ ]:
# df = pd.read_csv('Altered CSVs/after_cleaning.csv')

In [9]:
# Tokenize the descriptions
df['tokens'] = df['description'].apply(word_tokenize)

# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [10]:
# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

In [11]:
# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [120]:
# df.to_csv('Altered CSVs/after_tokenization.csv', index=False)

# Sentance Transformer / Embeddings

In [ ]:
# df = pd.read_csv('Altered CSVs/MutliLabelBinarized.csv')

In [12]:
model = SentenceTransformer('all-MiniLM-L6-v2')

df['title'] = df['title'].fillna('')
df['description'] = df['description'].fillna('')

# Ensure tags (which are lists) are converted to a single string before concatenation
df['tags_text'] = df['tags'].apply(
    lambda x: ' '.join(x) if isinstance(x, (list, tuple)) else str(x)
)

texts = (df['title'] + ' ' + df['description'] + ' ' + df['tags_text']).tolist()

text_embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)

df['embedding'] = list(text_embeddings)

Batches:   0%|          | 0/1590 [00:00<?, ?it/s]

c:\Users\vince\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [122]:
# df.to_csv('Altered CSVs/with_embeddings.csv', index=False)

# Normalization

## Min-Max

In [ ]:
# df = pd.read_csv('Altered CSVs/with_embeddings.csv')

**Applied for Ratings**

In [13]:
rating_dict = {
    'Overwhelmingly Positive': 9,
    'Very Positive': 8,
    'Positive': 7,
    'Mostly Positive': 6,
    'Mixed': 5,
    'Mostly Negative': 4,
    'Negative': 3,
    'Very Negative': 2,
    'Overwhelmingly Negative': 1
}

df['rating_normalized'] = (df['rating'].map(rating_dict) - 1) / 8

## Log Normalizing

**Applied for Positive Ratio, Price, and Review Count**

In [14]:
df['positive_ratio_log'] = np.log1p(df['positive_ratio'])
df['price_log'] = np.log1p(df['price_final'])
df['user_reviews_log'] = np.log1p(df['user_reviews'])

In [125]:
# df.to_csv('Altered CSVs/normalized.csv', index=False)

# Concatenating Features

In [ ]:
# df = pd.read_csv('Altered CSVs/normalized.csv')

In [15]:
embeddings = text_embeddings

tags = tag_matrix

numerics = df[['price_log', 'positive_ratio_log', 'user_reviews_log']].values

X = np.hstack([numerics*0.6, embeddings*0.1, tags*2.0])

cs_matrix = cosine_similarity(X)

# np.save('hstack_data.npy', X)

np.save('cs_matrix.npy', cs_matrix)

In [ ]:
X = X.astype(np.float32)

svd = TruncatedSVD(n_components=128, random_state=0)
Xr = svd.fit_transform(X).astype(np.float32)

norms = np.linalg.norm(Xr, axis=1, keepdims=True) + 1e-9
Xn = (Xr / norms).astype(np.float32)

feat_cols = [f"feat_{i}" for i in range(Xn.shape[1])]
export_df = pd.concat([df[["title"]].reset_index(drop=True),
pd.DataFrame(Xn, columns=feat_cols)], axis=1)

In [100]:
df = pd.read_parquet("games_with_features.parquet")

In [103]:
# Find nan
df.isna().sum()

title       0
feat_0      0
feat_1      0
feat_2      0
feat_3      0
           ..
feat_123    0
feat_124    0
feat_125    0
feat_126    0
feat_127    0
Length: 129, dtype: int64

In [99]:
export_df.to_parquet("games_with_features.parquet", index=False)

In [105]:
import numpy as np
hstack_data = np.load('hstack_data.npy')
hstack_data.shape, hstack_data

((50872, 828),
 array([[0.95879431, 1.7770605 , 3.07848506, ..., 0.        , 0.        ,
         0.        ],
        [0.55351649, 1.78173892, 1.23641698, ..., 0.        , 0.        ,
         0.        ],
        [1.10878541, 1.8130398 , 3.28891403, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [1.37359488, 1.79992387, 2.81163503, ..., 0.        , 0.        ,
         0.        ],
        [1.1561487 , 1.82573928, 1.76753624, ..., 0.        , 0.        ,
         0.        ],
        [0.64377516, 1.79545455, 1.9906935 , ..., 0.        , 0.        ,
         0.        ]]))

# Cosine Similarity

In [ ]:
# df = pd.read_csv('Altered CSVs/merged_game_data.csv')

In [21]:
# df = pd.read_csv('Altered CSVs/merged_game_data.csv')
# df = pd.read_csv('Altered CSVs/normalized.csv')

# cs_matrix = np.load('cs_matrix.npy')

def recommend(df, appid, cs_matrix, k=10):
    
    index = df[df['app_id'] == appid].index[0]
    pos = df.index.get_loc(index)
    
    scores = cs_matrix[pos].copy()
    scores[pos] = -np.inf

    indexes = np.argsort(scores)[-k:][::-1]
    return df_og.iloc[indexes]

In [82]:
cs_matrix.shape, df.shape

((50872, 50872), (50872, 456))

In [94]:
# open hstack
import numpy as np
hstack_data = np.load('hstack_data.npy')
hstack_data.shape,hstack_data

((50872, 828),
 array([[0.95879431, 1.7770605 , 3.07848506, ..., 0.        , 0.        ,
         0.        ],
        [0.55351649, 1.78173892, 1.23641698, ..., 0.        , 0.        ,
         0.        ],
        [1.10878541, 1.8130398 , 3.28891403, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [1.37359488, 1.79992387, 2.81163503, ..., 0.        , 0.        ,
         0.        ],
        [1.1561487 , 1.82573928, 1.76753624, ..., 0.        , 0.        ,
         0.        ],
        [0.64377516, 1.79545455, 1.9906935 , ..., 0.        , 0.        ,
         0.        ]]))

In [22]:
# Killing Floor 2
rec = recommend(df, 232090, cs_matrix)
rec[['app_id', 'title', 'rating', 'user_reviews', 'positive_ratio', 'price_final','tags', 'description']]

,app_id,title,rating,user_reviews,positive_ratio,price_final,tags,description
12687,323190,Frostpunk,Very Positive,77955,92,30.0,[],
13262,686810,Hell Let Loose,Very Positive,68869,84,29.0,[],
13179,412020,Metro Exodus,Very Positive,82022,89,30.0,[],
14161,848450,Subnautica: Below Zero,Very Positive,74092,91,30.0,[],
15401,361420,ASTRONEER,Very Positive,94605,91,30.0,[],
47947,601150,Devil May Cry 5,Overwhelmingly Positive,71034,95,30.0,[],
48422,1167630,Teardown,Overwhelmingly Positive,71271,96,30.0,[],
47405,8870,BioShock Infinite,Very Positive,99379,93,30.0,[],
14401,359320,Elite Dangerous,Mostly Positive,68600,76,30.0,[],
13274,1332010,Stray,Overwhelmingly Positive,111376,97,30.0,[],

In [67]:
# ELDEN RING
rec = recommend(df, 1245620, cs_matrix)
rec[['app_id', 'title', 'rating', 'user_reviews', 'positive_ratio', 'price_final','tags', 'description']]

,app_id,title,rating,user_reviews,positive_ratio,price_final,tags,description
13803,221100,DayZ,Mostly Positive,296845,74,45.0,[],dayz 0 action adventure parkour third p...
12689,1063730,New World,Mostly Positive,222345,70,40.0,[],new world 0 action adventure parkour th...
14163,1091500,Cyberpunk 2077,Very Positive,557051,80,60.0,[],cyberpunk 2077 0 action adventure parko...
48514,1238810,Battlefield™ V,Mostly Positive,141836,70,50.0,[],battlefield v 0 action adventure parkou...
15719,1172620,Sea of Thieves 2023 Edition,Very Positive,253844,90,40.0,[],sea of thieves 2023 edition 0 action ad...
14434,275850,No Man's Sky,Mostly Positive,209971,76,60.0,[],no mans sky 0 action adventure parkour ...
14770,1086940,Baldur's Gate 3,Overwhelmingly Positive,269840,95,60.0,[],baldurs gate 3 0 action adventure parko...
15364,261550,Mount & Blade II: Bannerlord,Very Positive,177725,87,50.0,[],mount blade ii bannerlord 0 action adv...
13598,976730,Halo: The Master Chief Collection,Very Positive,192874,92,40.0,[],halo the master chief collection 0 acti...
12658,594650,Hunt: Showdown,Very Positive,136385,83,40.0,[],hunt showdown 0 action adventure parkou...

In [66]:
# Titanfall 2
rec = recommend(df, 1237970, cs_matrix)
rec[['app_id', 'title', 'rating', 'user_reviews', 'positive_ratio', 'price_final','tags', 'description']]

,app_id,title,rating,user_reviews,positive_ratio,price_final,tags,description
47817,774171,Muse Dash,Very Positive,86591,90,3.0,[],muse dash 0 action adventure parkour th...
3372,322170,Geometry Dash,Very Positive,239081,93,4.0,[],geometry dash 0 action adventure parkou...
47548,238320,Outlast,Overwhelmingly Positive,75391,96,3.0,[],outlast 0 action adventure parkour thir...
15281,1794680,Vampire Survivors,Overwhelmingly Positive,197109,98,5.0,[],vampire survivors 0 action adventure pa...
47791,431960,Wallpaper Engine,Overwhelmingly Positive,637341,98,4.0,[],wallpaper engine 0 action adventure par...
50781,945360,Among Us,Very Positive,587821,92,3.0,[],among us 0 action adventure parkour thi...
47394,3590,Plants vs. Zombies GOTY Edition,Overwhelmingly Positive,100864,97,5.0,[],plants vs zombies goty edition 0 action...
47790,433340,Slime Rancher,Overwhelmingly Positive,97997,97,5.0,[],slime rancher 0 action adventure parkou...
48013,674940,Stick Fight: The Game,Very Positive,89774,93,5.0,[],stick fight the game 0 action adventure...
47647,304430,INSIDE,Overwhelmingly Positive,45867,96,2.0,[],inside 0 action adventure parkour third...

In [65]:
# Insurgency Sandstorm
rec = recommend(df, 581320, cs_matrix)
rec[['app_id', 'title', 'rating', 'user_reviews', 'positive_ratio', 'price_final','tags', 'description']]

,app_id,title,rating,user_reviews,positive_ratio,price_final,tags,description
14166,220200,Kerbal Space Program,Overwhelmingly Positive,94712,95,10.0,[],kerbal space program 0 action adventure...
47383,400,Portal,Overwhelmingly Positive,117868,98,10.0,[],portal 0 action adventure parkour third...
47523,219740,Don't Starve,Overwhelmingly Positive,87184,96,10.0,[],dont starve 0 action adventure parkour ...
13504,22380,Fallout: New Vegas,Overwhelmingly Positive,147417,96,10.0,[],fallout new vegas 0 action adventure pa...
47933,582660,Black Desert,Mostly Positive,49539,76,10.0,[],black desert 0 action adventure parkour...
47742,391540,Undertale,Overwhelmingly Positive,182534,96,10.0,[],undertale 0 action adventure parkour th...
14774,1118200,People Playground,Overwhelmingly Positive,195164,98,10.0,[],people playground 0 action adventure pa...
47832,470220,UNO,Mostly Positive,35495,73,10.0,[],uno 0 action adventure parkour third pe...
15278,960090,Bloons TD 6,Overwhelmingly Positive,239938,97,14.0,[],bloons td 6 0 action adventure parkour ...
47561,239030,Papers Please,Overwhelmingly Positive,57117,97,10.0,[],papers please 0 action adventure parkou...

In [64]:
# Halo The Master Chief Collection
rec = recommend(df, 976730, cs_matrix)
rec[['app_id', 'title', 'rating', 'user_reviews', 'positive_ratio', 'price_final','tags', 'description']]

,app_id,title,rating,user_reviews,positive_ratio,price_final,tags,description
47760,394360,Hearts of Iron IV,Very Positive,176243,92,40.0,[],hearts of iron iv 0 action adventure pa...
15097,782330,DOOM Eternal,Very Positive,153466,91,40.0,[],doom eternal 0 action adventure parkour...
12658,594650,Hunt: Showdown,Very Positive,136385,83,40.0,[],hunt showdown 0 action adventure parkou...
15719,1172620,Sea of Thieves 2023 Edition,Very Positive,253844,90,40.0,[],sea of thieves 2023 edition 0 action ad...
15809,534380,Dying Light 2 Stay Human,Mostly Positive,113138,79,30.0,[],dying light 2 stay human 0 action adven...
12740,294100,RimWorld,Overwhelmingly Positive,140668,98,35.0,[],rimworld 0 action adventure parkour thi...
15397,489830,The Elder Scrolls V: Skyrim Special Edition,Very Positive,138503,94,40.0,[],the elder scrolls v skyrim special edition 0 ...
48601,1326470,Sons Of The Forest,Very Positive,128626,83,30.0,[],sons of the forest 0 action adventure p...
47793,427520,Factorio,Overwhelmingly Positive,134384,96,35.0,[],factorio 0 action adventure parkour thi...
14401,359320,Elite Dangerous,Mostly Positive,68600,76,30.0,[],elite dangerous 0 action adventure park...